# $Id: makefile,v 1.1 2001/05/17 20:07:52 pcharles Exp $
#
#   sourceforge java tree makefile
#
MAKE_HOME = /home/zxj/project/IdeaProjects/jpcap-0.01.16/make
TARGETS = \
	net/sourceforge

# default target and tree traversal for standard targets like 'all' or 'clean'
include ${MAKE_HOME}/standard_target_chain.makefile
include ${MAKE_HOME}/os.makefile
